custom_azureus_usertype:
    resource: "@CustomAzureusBundle/Resources/config/routing/userinfo.yml"
    prefix:   /usertype

custom_azureus_admin_user:
    resource: "@CustomAzureusBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user
 
custom_azureus_homepage:
    path:     /
    defaults: { _controller: CustomAzureusBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: CustomAzureusBundle:Security:login }
    
login_check:
    path:     /login_check

logout:
    pattern:  /logout
      
profile_edit:
    path:     /edit_profile
    defaults: { _controller: "CustomAzureusBundle:User:editProfile" }
    
profile_update:
    path:     /edit_profile/update
    defaults: { _controller: "CustomAzureusBundle:User:profileUpdate" }

user_created:
    path:     /succes
    defaults: { _controller: "CustomAzureusBundle:Default:succes" }