custom_azureus_usertype:
    resource: "@CustomAzureusBundle/Resources/config/routing/userinfo.yml"
    prefix:   /usertype

custom_azureus_admin_user:
    resource: "@CustomAzureusBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

 
custom_azureus_homepage:
    path:     /
    defaults: { _controller: CustomAzureusBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: CustomAzureusBundle:Security:login }
    
login_check:
    path:     /login_check

logout:
    pattern:  /logout
    
account_register:
    path:     /register
    defaults: { _controller: CustomAzureusBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: CustomAzureusBundle:Account:create }