custom_azureus_usertype:
    resource: "@CustomAzureusBundle/Resources/config/routing/userinfo.yml"
    prefix:   /usertype

custom_azureus_admin_user:
    resource: "@CustomAzureusBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user
    
custom_azureus_art:
    resource: "@CustomAzureusBundle/Resources/config/routing/art.yml"
    prefix:   /art
    
custom_azureus_post:
    resource: "@CustomAzureusBundle/Resources/config/routing/post.yml"
    prefix:   /post
 
custom_azureus_homepage:
    path:     /
    defaults: { _controller: CustomAzureusBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: CustomAzureusBundle:Security:login }

login_check:
    path:     /login_check

logout:
    pattern:  /logout

profile_edit:
    path:     /edit_profile
    defaults: { _controller: "CustomAzureusBundle:User:editProfile" }

profile_update:
    path:     /edit_profile/update
    defaults: { _controller: "CustomAzureusBundle:User:profileUpdate" }

user_created:
    path:     /succes
    defaults: { _controller: "CustomAzureusBundle:Default:succes" }

show_profile:
    path: /user/{username}
    defaults: { _controller: "CustomAzureusBundle:User:showProfile" }

show_gallery:
    path: /user/{username}/gallery
    defaults: { _controller: "CustomAzureusBundle:User:showGallery" }

show_journal:
    path: /user/{username}/journal
    defaults: { _controller: "CustomAzureusBundle:User:showJournal" }

change_passwd:
    path: /change_passwd
    defaults: { _controller: "CustomAzureusBundle:ChangePassword:changePasswd" }

change_passwd_success:
    path: /succes
    defaults: { _controller: "CustomAzureusBundle:ChangePassword:succes" }